<?

class BattleEventPriority
{
	const DISPOSED_BEFORE_MAIN_EVENT = 100;
	const DISPOSED_REVENGE_BUFF = 90;
	const DAMAGED_BEFORE_MAIN_EVENT = 100;
	const DAMAGED_DODGE_BUFF = 90;
	const TURN_EVENT = -100;
}